package dotnet.system.runtime.interopservices;

@:fakeEnum(Int) @:native("System.Runtime.InteropServices.TYPEFLAGS")
extern enum TYPEFLAGS {
  TYPEFLAG_FAPPOBJECT;
  TYPEFLAG_FCANCREATE;
  TYPEFLAG_FLICENSED;
  TYPEFLAG_FPREDECLID;
  TYPEFLAG_FHIDDEN;
  TYPEFLAG_FCONTROL;
  TYPEFLAG_FDUAL;
  TYPEFLAG_FNONEXTENSIBLE;
  TYPEFLAG_FOLEAUTOMATION;
  TYPEFLAG_FRESTRICTED;
  TYPEFLAG_FAGGREGATABLE;
  TYPEFLAG_FREPLACEABLE;
  TYPEFLAG_FDISPATCHABLE;
  TYPEFLAG_FREVERSEBIND;
  TYPEFLAG_FPROXY;
}

