package dotnet.system.runtime.interopservices.comtypes;

@:fakeEnum(Int) @:native("System.Runtime.InteropServices.ComTypes.FUNCFLAGS")
extern enum FUNCFLAGS {
  FUNCFLAG_FRESTRICTED;
  FUNCFLAG_FSOURCE;
  FUNCFLAG_FBINDABLE;
  FUNCFLAG_FREQUESTEDIT;
  FUNCFLAG_FDISPLAYBIND;
  FUNCFLAG_FDEFAULTBIND;
  FUNCFLAG_FHIDDEN;
  FUNCFLAG_FUSESGETLASTERROR;
  FUNCFLAG_FDEFAULTCOLLELEM;
  FUNCFLAG_FUIDEFAULT;
  FUNCFLAG_FNONBROWSABLE;
  FUNCFLAG_FREPLACEABLE;
  FUNCFLAG_FIMMEDIATEBIND;
}

