package unityengine;

@:fakeEnum(Int) @:native("UnityEngine.TextureFormat")
extern enum TextureFormat {
  Alpha8;
  ARGB4444;
  RGB24;
  RGBA32;
  ARGB32;
  RGB565;
  DXT1;
  DXT5;
  RGBA4444;
  BGRA32;
  PVRTC_RGB2;
  PVRTC_RGBA2;
  PVRTC_RGB4;
  PVRTC_RGBA4;
  ETC_RGB4;
  ATC_RGB4;
  ATC_RGBA8;
  ATF_RGB_DXT1;
  ATF_RGBA_JPG;
  ATF_RGB_JPG;
  EAC_R;
  EAC_R_SIGNED;
  EAC_RG;
  EAC_RG_SIGNED;
  ETC2_RGB;
  ETC2_RGBA1;
  ETC2_RGBA8;
  ASTC_RGB_4x4;
  ASTC_RGB_5x5;
  ASTC_RGB_6x6;
  ASTC_RGB_8x8;
  ASTC_RGB_10x10;
  ASTC_RGB_12x12;
  ASTC_RGBA_4x4;
  ASTC_RGBA_5x5;
  ASTC_RGBA_6x6;
  ASTC_RGBA_8x8;
  ASTC_RGBA_10x10;
  ASTC_RGBA_12x12;
  PVRTC_2BPP_RGB;
  PVRTC_2BPP_RGBA;
  PVRTC_4BPP_RGB;
  PVRTC_4BPP_RGBA;
}

